spring.application.name=ERP-Practice

# ===== DataSource =====
spring.datasource.url=jdbc:mysql://localhost:3306/erp_practice?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=0000
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== jOOQ =====
spring.jooq.sql-dialect=MYSQL

# ===== MongoDB =====
spring.data.mongodb.uri=mongodb://localhost:27017/erp_practice

# ===== Jackson =====
spring.jackson.time-zone=Asia/Seoul
spring.jackson.serialization.write-dates-as-timestamps=false

# ===== Flyway =====
spring.flyway.validate-on-migrate=false

# ===== OpenAPI =====
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
